FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

CMD ["sh", "-c", "rm -rf node_modules/.bin && npm install && npm start -- --host 0.0.0.0 --poll 2000"]